language: node_js
sudo: false
node_js:
  - "7"

cache:
  yarn: true
  directories:
    - ./node_modules

before_script:
  - yarn global add @angular/cli

script:
  - yarn install
  - ng build -prod

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  github_token: $GITHUB_TOKEN
  on:
    branch: master